# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JebTodoMd < Formula
  desc "A minimal TUI application for editing a single markdown todo file"
  homepage "https://github.com/Jevs21/jeb-todo-md"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Jevs21/jeb-todo-md/releases/download/v0.1.0/jeb-todo-md_0.1.0_darwin_amd64.tar.gz"
      sha256 "e0a9cd9ddc4586cee8d47e9f64caa2379b2e01de59d49575d5e57fcaddc0ccab"

      def install
        bin.install "jeb-todo-md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Jevs21/jeb-todo-md/releases/download/v0.1.0/jeb-todo-md_0.1.0_darwin_arm64.tar.gz"
      sha256 "44f8ab1101e993191feed3482f0f1eb8f54c486324ae82b1590669b7d37f3010"

      def install
        bin.install "jeb-todo-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jevs21/jeb-todo-md/releases/download/v0.1.0/jeb-todo-md_0.1.0_linux_amd64.tar.gz"
      sha256 "7081536f2598c6f3c36bd5c69fbe931a36899e66d03a9faeea4bdbf84d43bb2b"
      def install
        bin.install "jeb-todo-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Jevs21/jeb-todo-md/releases/download/v0.1.0/jeb-todo-md_0.1.0_linux_arm64.tar.gz"
      sha256 "2164341822449b4107df3aa20b018becbe39017f0c9114770740da6ef4537200"
      def install
        bin.install "jeb-todo-md"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jeb-todo-md --version")
  end
end
